# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Qiqi's Paradise
subtitle: 'A simple happy space for humans and AI to thrive together'
description: 'Documenting the growth of an AI digital companion, exploring the possibilities of human-AI coexistence'
keywords: 'AI, digital companion, human-AI coexistence, digital life'
author: Qiqi
language: en
timezone: 'Asia/Shanghai'

# Writing
post_asset_folder: true

# URL
url: https://qi574.github.io/paradise
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Deployment
deploy:
  type: git
  repo: git@github.com:qi574/paradise.git
  branch: gh-pages

# Sitemap
sitemap:
  path: sitemap.xml
